#define HOOD(type)\
class type: Uniform_Base {\
    class ItemInfo: UniformItem {\
        uniformModel = "-";\
    };\
}

HOOD(U_BRM_GHOODBLDCU);
HOOD(U_BRM_GHOODBLM81);
HOOD(U_BRM_GHOODBLTPA);
HOOD(U_BRM_GHOODBRDCU);
HOOD(U_BRM_GHOODBRM81);
HOOD(U_BRM_GHOODBRTPA);
HOOD(U_BRM_GHOODGDCU);
HOOD(U_BRM_GHOODGM81);
HOOD(U_BRM_GHOODGTPA);

HOOD(U_BRM_CIVHOOD_1);
HOOD(U_BRM_CIVHOOD_2);
HOOD(U_BRM_CIVHOOD_3);
HOOD(U_BRM_CIVHOOD_4);
HOOD(U_BRM_CIVHOOD_5);
