#define EBATTLE(type)\
class type: BRM_EBattleUNI_Green {\
    class ItemInfo: ItemInfo {\
        mass = 40;\
    };\
}

class BRM_EBattleUNI_Green: BRM_BattleUNI_Base {
    class ItemInfo: UniformItem {
        mass = 40;
    };
};

EBATTLE(BRM_EBattleUNI_Black);
EBATTLE(BRM_EBattleUNI_BLUM);
EBATTLE(BRM_EBattleUNI_Brown);
EBATTLE(BRM_EBattleUNI_EMR);
EBATTLE(BRM_EBattleUNI_NavyB);
EBATTLE(BRM_EBattleUNI_CZRAIN);
EBATTLE(BRM_EBattleUNI_SyrDIGI);
EBATTLE(BRM_EBattleUNI_EGRAIN);
EBATTLE(BRM_EBattleUNI_T07PLAT);
EBATTLE(BRM_EBattleUNI_T07NAVY);
EBATTLE(BRM_EBattleUNI_T07UNI);
EBATTLE(BRM_EBattleUNI_T07ARTY);

EBATTLE(BRM_EBattleUNIRS_Black);
EBATTLE(BRM_EBattleUNIRS_BLUM);
EBATTLE(BRM_EBattleUNIRS_Brown);
EBATTLE(BRM_EBattleUNIRS_EMR);
EBATTLE(BRM_EBattleUNIRS_Green);
EBATTLE(BRM_EBattleUNIRS_NavyB);
EBATTLE(BRM_EBattleUNIRS_CZRAIN);
EBATTLE(BRM_EBattleUNIRS_SyrDIGI);
EBATTLE(BRM_EBattleUNIRS_EGRAIN);
EBATTLE(BRM_EBattleUNIRS_T07PLAT);
EBATTLE(BRM_EBattleUNIRS_T07NAVY);
EBATTLE(BRM_EBattleUNIRS_T07UNI);
EBATTLE(BRM_EBattleUNIRS_T07ARTY);

EBATTLE(BRM_EBattleUNITS_Black);
EBATTLE(BRM_EBattleUNITS_BLUM);
EBATTLE(BRM_EBattleUNITS_Brown);
EBATTLE(BRM_EBattleUNITS_EMR);
EBATTLE(BRM_EBattleUNITS_Green);
EBATTLE(BRM_EBattleUNITS_NavyB);
EBATTLE(BRM_EBattleUNITS_CZRAIN);
EBATTLE(BRM_EBattleUNITS_SyrDIGI);
EBATTLE(BRM_EBattleUNITS_EGRAIN);
EBATTLE(BRM_EBattleUNITS_T07PLAT);
EBATTLE(BRM_EBattleUNITS_T07NAVY);
EBATTLE(BRM_EBattleUNITS_T07UNI);
EBATTLE(BRM_EBattleUNITS_T07ARTY);
